### ISSUE TITLE
Level 5 Gyatt Rizz Copypasta or Level 5 Gyatt Rizz Livvy Dunne Rizzing Up Baby Gronk

### ISSUE THREAD

**Issue by EliasKsl** [FirefoxyleGibus/ChatMD-Frontend#19]
Sometimes I wake up and think about skibidi toilet. I love the sensation of watching a skibidi toilet video, it brings me so much fucking sexual pleasure. I build up with ecstasy when I hear that first note of a skibidi toilet video. God, I wish skibidi toilet was real. If skibidi toilet was real, everyday I would go give it a kiss and let it suck my meat. But alas we live in this cruel cruel world without skibidi toilet. Words cannot describe how much I love it, My family has tried to make me stop watching them but when they do I bark and bite and claw. Everytime I take a shit I pretend skibidi toilet is right under me devouring my brown excrement. Sometimes I imagine Kak from egofilms as a skibidi toilet and I immediately blow my load in my pants. I wish skibidi toilet woiuld lick my sweet luscious cheeks. Skibidi toilet is the only thing that brings me true joy anymore. I watch skibidi toilet any time I can. One time I saw Donald Trump and wondered what he'd look like as a skibidi toilet guy. The lore of skibidi toilet is so deep and complex and it turns me on so much. Imagine if skibidi toilet had breasts 🤤 . God, even the idea of it gets me hard. Please don't judge me, Skibidi toilet is really sexy and it's not my fault it decided to be that f-ing hot. If you disrespect skibidi toilet in my presence you're going to get a knuckle toilet pal 😡. I have the skibidi song playing 24/7 in my headphones to the point if even see/hear the letters s-k-i-b-i-d-i-t-o-i-l-e-t I start acting out. Skibidi toilet makes me foam at the mouth. God, sometimes I wish skibidi toilet would pop out my toilet one day. I would happily let it turn me into one of it's kind. I wonder in the afterlife if I'll see skibidi toilet. 
![crying without no body](https://github.com/FirefoxyleGibus/ChatMD-Frontend/assets/120009445/3e58baf0-8dfa-4d79-9c25-de89f3568821)

**Comment by HastagGuigui** [comment]
erm. what the sigma?

**Comment by EliasKsl** [comment]
you fell off + ratio
