### ISSUE TITLE
On peut pas co sur le web

### ISSUE THREAD

**Issue by FirefoxyleGibus** [FirefoxyleGibus/ChatMD-Frontend#6]
BAH OUI
mon code marche pas

VOUS CONNAISSEZ LA DEFINITION DE LA FOLIE
C'EST MOI

**Comment by EliasKsl** [comment]
kys

**Comment by FirefoxyleGibus** [comment]
ok

**Comment by Louvtt** [comment]
adios

**Comment by HastagGuigui** [comment]
blåhaj coding 

![IMG20230619120407.jpg](https://github.com/FirefoxyleGibus/ChatMD-Frontend/assets/47950669/38d7f3a3-6501-4ce6-9a18-00045fc77628)

**Comment by Alekuso** [comment]
![FpFbMj-XgAEKhhT](https://github.com/FirefoxyleGibus/ChatMD-Frontend/assets/48645888/b57ed976-fc26-4704-acf0-54ff30203aa4)

**Comment by EliasKsl** [comment]
pourquoi il y a des blahaj ici
