### ISSUE TITLE
Little issues for you my fren

### ISSUE THREAD

**Issue by Louvtt** [FirefoxyleGibus/ChatMD-Frontend#8]
- Small glitch with refreshing the terminal so messages overlay each others
- Guigui can you make somethings for the buttons, the quit button is ugly plz it hurts
- We have duplication occuring when sending the messages, because we are also receiving it, idk if it is front end or backend but it is pretty annoying

Have a nice day im going to sleep zzzzz

**Comment by FirefoxyleGibus** [comment]
Did you use simu_backend.py or the backend made by Alex ?

**Comment by HastagGuigui** [comment]
- Overlayed messages are fixed!
- Message duplication has been fixed as well.

**Comment by HastagGuigui** [comment]
Everything has been fixed in the multithreading branch, gonna close this issue once it's merged with main

**Comment by HastagGuigui** [comment]
#9 fixed everything above
